### PR TITLE
Add iOS 14.2 to snapshot test matrix

### PR DESCRIPTION
**Pull request by NickEntin**

### CODE REVIEW

**Comment by NickEntin** [comment]
Ugh, `SnapshotTestingTests.testInvertColors` is giving me different results when I step through it with a debugger vs. run it regularly... and neither are correct 🙃

**Comment by NickEntin** [comment]
Now I'm getting the correct result when I step through it with a debugger (the snapshot I just added), but when it run it normally I still just get an all-black image.

**Review by efirestone — APPROVED** [review]

**Comment by NickEntin** [comment]
I manually compared these snapshot against the demo app, and they all match with a few exceptions:
* Some of the data table descriptions are off (already tracked by #7)
* Some of the tab bar descriptions have changed slightly (already tracked by #26)
* It looks like there's a new automatic hint for the `.allowsDirectInteraction` trait to "Use the rotor to enable Direct Touch for this app." I'll file an issue to look into this.
* VoiceOver thinks some of my switches belong in the dining room... yeah, I have no idea

https://user-images.githubusercontent.com/1857549/103620229-0056cd80-4ee8-11eb-97a7-f971c1ddfb2c.mov

**Comment by NickEntin** [comment]
I'm removing Travis CI as a required build since it isn't running the .com version right now (the .org version is passing, but will stop working soon). Hopefully we can migrate the iOS 12 tests over to GH Actions with #43.

Merging this now, then I'll add the iOS 14 CI build as a required PR check.

**Pull request merged**
