### PR TITLE
Hide text field and text view cursors while snapshotting

### LINKED ISSUE #15: Improve support for snapshotting views with text field cursors to prevent tests from flaking

### PR DESCRIPTION
**Pull request by NickEntin**
Resolves #15

### CODE REVIEW

**Comment by DavidBrunow** [comment]
You may have already considered and rejected this idea, but I've used `UITextField.appearance().tintColor = .clear` in the past to globally hide the cursors while creating snapshots.

**Comment by NickEntin** [comment]
> You may have already considered and rejected this idea, but I've used `UITextField.appearance().tintColor = .clear` in the past to globally hide the cursors while creating snapshots.

@DavidBrunow Great suggestion, but I don't think there's a way to restore the original tint colors after the snapshot using the appearance API.

**Comment by NickEntin** [comment]
Hmm the iOS 16 build is failing due to missing activation point targets. I've seen this issue locally too, but can't figure out what causes it. Sometimes the image just doesn't load.

```
	ActivationPointTests.testActivationPointEnabled()
	ActivationPointTests.testActivationPointEnabledWhenOverridden()
	-[ImpreciseObjectiveCTests testSimpleViewWithActivationPointAlways]
	-[ObjectiveCTests testSimpleViewWithActivationPointAlways]
	-[ObjectiveCTests testSimpleViewWithActivationPointDefault]
	SnapshotTestingTests.testShowingActivationPoint()
	SnapshotTestingTests.testShowingActivationPoint()
```

**Comment by NickEntin** [comment]
Filed #208 to track the activation point issue.

**Review by kruegermj — APPROVED** [review]

**Pull request merged**
